# name: Deploy Bruma to Prod

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-24.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Deploy using SSH
#         uses: appleboy/ssh-action@v1
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           password: ${{ secrets.SSH_PASSWORD }}
#           port: ${{ secrets.SSH_PORT }}
#           script: |
#             cd ${{ secrets.APP_PATH }}
#             git pull origin main
#             touch ./database/database.sqlite
#             composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist
#             php artisan migrate --force
#             npm i && npm run build
#             php artisan optimize
#             php artisan config:cache
#             php artisan route:cache
#             php artisan view:cache
